### ISSUE TITLE
Data resurrection when recreating formerly destroyed index

### ISSUE THREAD

**Issue by jxerome** [strapdata/elassandra#108]
After index destruction, the data in corresponding keyspace and tables are kept.
While recreating the index, former data is restored.
Expected behaviours, only the new data is available.

Note: Elassandra is used as an Elasticsearch implementation.

Script to reproduce: 
https://gist.github.com/jxerome/f8244f5eaa9725e0629f18b43ad5eaad

**Comment by vroyer** [comment]
Hi,

This is the default expected behavior, cassandra is your persistent primary data storage.

If you want to delete cassandra keyspace/table when deleting an Elasticsearch index (to use Elassandra as an Elasticsearch implementation), set the **drop_on_delete_index** parameter at the cluster or index level, as described in [Elassandra doc](http://doc.elassandra.io/en/latest/configuration.html#elassandra-settings).

Thanks.

**Comment by jxerome** [comment]
OK, I don't see how I can easily set that parameter when strating the docker container.

**Comment by vroyer** [comment]
Maybe you can run elassandra with the JVM option -Des.drop_on_delete_index=true ?

**Comment by jxerome** [comment]
Yes, the exact command is : 
docker run -d -P -e "JVM_OPTS=-Des.drop_on_delete_index=true" strapdata/elassandra
