### ISSUE TITLE
Production usage

### ISSUE THREAD

**Issue by ddorian** [strapdata/elassandra#123]
Anyone using in production ? What version, number of nodes etc ?

Thanks

**Comment by DBarthe** [comment]
v5.5.0.x is much more efficient, but documentation isn't fully updated yet.
You can follow cassandra recommendations but basically you'll need more disk space to store both lucene segments and cassandra files.

**Comment by fdsmax** [comment]
We are trying v5.5.0.3 in 12 nodes cluster in production for our [Thulya Cloud Apps and Social Network](http://png.to/w2L2SKf6). We will be migrating to v5.5.0.4 this week. Except the lack of the login and data security ([PasswordAuthenticator and CassandraAuthorizer](https://github.com/strapdata/elassandra/issues/49)) all others seem to look great. Currently for elasticsearch we have applied [Search Guard](https://github.com/floragunncom/search-guard) and left Cassandra (Strapdata) side by blocking the ports from the public access. I will be posting more updates soon in my blog at [Diwakar Padmaraju](https://thulya.com/diwakarpp)

**Comment by vroyer** [comment]
Hi,
Thanks a lot for your blog.
We have delivered a commercial Enterprise plugin providing Elasticsearch authentication and role based access control based on the Cassandra PasswordAuthenticator and CassandraAuthorizer.
Documentation is available at http://doc.elassandra.io/en/latest/enterprise.html#authentication-and-authorization <http://doc.elassandra.io/en/latest/enterprise.html#authentication-and-authorization>
Thanks.

**Comment by fdsmax** [comment]
Thank you for the pointer on the Enterprise plugin @vroyer . I have updated my blog post [Elassandra is an alternative for MongoDB as it combines the power of Cassandra and Elasticsearch](http://png.to/w2L2SKf6) with additional comments about the security features of the enterprise plugin. We will try to add this plugin to our production cluster.

**Comment by vroyer** [comment]
Ok, thanks for the blog.

You have mentioned the enterprise features (JMX, SSL, AAA, CBS) probably from a copy/past of the figure describing restrictions due to an invalid license. 
Of course, with a valid strapdata license, you don’t need to restart nodes to make changes to take effect or to monitor a new index.

If you want to try theses features, i can sent you a trial license and the plugin zip, just fill the trial form http://www.strapdata.com/trial/ <http://www.strapdata.com/trial/>  with 
your cluster name, datacenters names and number of nodes.

Thanks.

**Comment by fdsmax** [comment]
Thanks for the note on the valid strapdata license @vroyer . I will update my post accordingly. I have requested for the licence from my email ids diwakarpp {} gmail.com yesterday as well as diwakar {} thulya.com today. I would appreciate your reply so that we could decide whether to test and use the enterprise plugin.

**Comment by vroyer** [comment]
Dr Mr Padmaraju,

Here is a one month trial license for the elassandra enterprise plugin, and the plugin itself.
Please follow the installation and usage instructions available at http://doc.elassandra.io/en/latest/enterprise.html#installation <http://doc.elassandra.io/en/latest/enterprise.html#installation>
This plugin is still a beta version and feedback about any issue is welcome.
I remain at your disposal to respond to any questions you may have.








Best regards,
Vincent Royer
Email: vroyer@strapdata.com
Mobile: +33 7 83 18 25 40
http://www.strapdata.com

**Comment by mimarpe** [comment]
Are the elasticsearch related metrics only available in the enterprise edition? I'm using something like the jmx exporter, but there are no MBeans available in JMX related to ES or anything else than the usual JVM and Cassandra.
Otherwise how to reach those metrics?
Is the grafana dashboard also only enterprise?
Thanks!
