### ISSUE TITLE
full debian and ubuntu support

### ISSUE THREAD

**Issue by ChrisFeldmeier** [strapdata/elassandra#13]
This weekend I will work on a new startup script and installation guide for installing elassandra on debian or ubuntu. Please no longer use the debian init script because it contains some bugs.
Thanks.

**Comment by ghost** [comment]
Hi,
Is it in progress or done or another state ?
Because I'll setup it soon on Debian Jessie and I want the best way.
Thanks

**Comment by vroyer** [comment]
Hi,
Yes, it's on going, a debian package should be available in a couple of weeks.
Right now, you can unzip the tarball, set your CASSANDRA_HOME, and run **bin/cassandra -e** to start elassandra.
Thanks.

**Comment by ChrisFeldmeier** [comment]
https://github.com/vroyer/elassandra/wiki/Setup-Elassandra-on-Debian

**Comment by xcourmont** [comment]
Hi, 

I just have published a debian like pakage, with installation method : 
https://github.com/vroyer/elassandra/wiki/Install-Elassandra-with-DEB-(Debian,Ubuntu...)

Feel free to try it and send your comments...

**Comment by ddorian** [comment]
@xcourmont 
I get this error after following the guide. For some reason it's getting the wrong path on ubuntu 14.04:
![virtualbox_ubuntu 14 04 server 32bit _06_07_2016_13_39_19](https://cloud.githubusercontent.com/assets/1592898/16621510/c1b45978-4396-11e6-9afb-f20ddb35139b.png)

**Comment by xcourmont** [comment]
hello,

the DNS name packages.elassandra.io was ko for a few days. That could explain why you've got this issue. 
A new release will be available, perhaps this week-end... 

I will release a new documentation, more detailed.

Beside that, I don't have tested on ubuntu server...
Remarks and suggestions are heavily appreciated

Regards

**Comment by ddorian** [comment]
@xcourmont Thanks, now I can install it with apt-get. But I have a new issue when I manually run it with /opt/elassandra/bin/cassandra -e and I don't understand why:

![virtualbox_ubuntu 14 04 server 32bit _11_07_2016_18_37_30](https://cloud.githubusercontent.com/assets/1592898/16738600/ac6becb2-4796-11e6-83b7-50038a952cde.png)

**Comment by xcourmont** [comment]
Hello,
there is no errors on your screen shot. so, it's difficult to see why you can't start elassandra.

Which version do you use ? 2.1.1-15 ?
Do you use the cassandra user ?

If not, have you set CASSANDRA_HOME and CASSANDRA_CONF to point to /opt/elassandra and /opt/elassandra/conf

You can also find some useful debugging info in elassandra logs (/opt/elassandra/logs).

I will install ubuntu server soon, and see if there is some issue with it...

Regards

**Comment by ddorian** [comment]
@xcourmont 
I'm using 2.1.1-14 and changed to the cassandra user on the screenshot.

![virtualbox_ubuntu 14 04 server 32bit _12_07_2016_11_45_34](https://cloud.githubusercontent.com/assets/1592898/16762844/978d9706-4826-11e6-9757-d36d622283bd.png)

Though now I can't uninstall elassandra to then install the new version:
![virtualbox_ubuntu 14 04 server 32bit _12_07_2016_11_49_38](https://cloud.githubusercontent.com/assets/1592898/16762877/be3f7d10-4826-11e6-980b-790c24585505.png)

**Comment by xcourmont** [comment]
Hello,

For your deinstallation problem :
I just try to uninstall on debian 8 and it works !!!
As soon as possible, I will install ubuntu and try this package to correct the issue.

what you can do 

To help me, try, as root, to run : 

set -xv
/var/lib/dpkg/info/elassandra.prerm
and send me the result.

To force uninstall of this package : 
put "exit 0" at the beginning of /var/lib/dpkg/info/elassandra.prerm, and retry to deinstall ...

Beside that, it seems that it is sigar library which stop java execution. Is your OS is 32 bit (because, the reported sigar version is 32 bit). and did you try the command suggested 
execstack -c /opt/elassandra/lib/sigar-bin/libsigar-x86-linux.so ?

Which java version do you use ?
Regards

**Comment by ddorian** [comment]
@xcourmont 
Running set -xv .... didn't return anything, just completed.
Yes the OS is 32bit.

While doing the execstack command I get:::

![virtualbox_ubuntu 14 04 server 32bit _12_07_2016_20_11_02](https://cloud.githubusercontent.com/assets/1592898/16778132/d3020650-486c-11e6-8662-4b8898196ab6.png)

Uninstalling is not a big deal for now, mostly running it.

Thanks

**Comment by xcourmont** [comment]
Hi,

"set -xv" is only used  to have debugging informations for scripts !!!
What is really interesting is the result of /var/lib/dpkg/info/elassandra.prerm execution (the script used when you remove elassandra package on debians like systems).

Beside that, I think that if you can't remove package, chances are that you will neither be able to upgrade  !!!

execstack is used to set some ELF informations on the executables, or shared libraries. It's related to security, and so, I think you must be root (or sudo) to succeed in this operation.

Regards

**Comment by SympleSynz** [comment]
Hi,

I'm working on a Big Data project for a class, and we are wanting to use Elassandra to access our twitter data. We are using Ubuntu 16 on AWS, but we are unable to follow the debian/ubuntu install in the docs because there is no Elassandra package for apt-get.  Was this removed or was the package renamed?

**Comment by DBarthe** [comment]
Hi @Synz0331,

This debian package is outdated, but we made a new one we did not publish yet.
It's gonna be available soon. If you need it now I can send you a copy.

**Comment by SympleSynz** [comment]
Hi @DBarthe ,

I would really appreciate it if we could get a copy of the new debian package.  We ended up finding the outdated one with "dpkg -i elassandra_2.1.1-18.1.4_all.deb" and discovered that it wasn't spinning up the ports properly.

**Comment by DBarthe** [comment]
Hi @Synz0331,

You can download deb file here: [https://file.town/download/80qu0z6dkjz9edxoy4ui39k1m](https://file.town/download/80qu0z6dkjz9edxoy4ui39k1m)
(ensure sha1sum is 93ccc9af82954492171e6edffc1c7f13ad9450a6).

To use it on Ubuntu 16.04 with openjdk-8:
```bash
$ sudo apt-get update
$ sudo apt-get install openjdk-8-jre-headless python
$ sudo dpkg -i elassandra-2.4.2-SNAPSHOT_all.deb
```
Cassandra should start automatically, ensure the daemon is active:
```bash
$ sudo systemctl status cassandra
```
Logs are in `/var/log/cassandra/system.log`.

Probably you want to use cqlsh:
```bash
$ sudo apt-get install python-pip
$ sudo pip install cqlsh
$ cqlsh  --cqlversion=3.4
```
(notice the use of `--cqlversion=3.4`)

In order to access Cassandra from outside your host, or to setup a multi-nodes cluster, you have to configure `/etc/cassandra/cassandra.yaml`. You can refer to the cassandra 3.0.10 [documentation](http://docs.datastax.com/en/cassandra/3.0/)

Please let me know if you encounter some troubles, this is not a stable release.

**Comment by SympleSynz** [comment]
hi @DBarthe 

The installation of the new debian package for Ubuntu 16 worked nearly flawlessly.  The only issue we ran into on the install was that nodetool isn't working.  It came back as an error. 
```
ubuntu@aws:/etc/cassandra$ nodetool --version
/usr/bin/nodetool: 25: [: missing ]
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: io/airlift/command/ParseArgumentsMissingException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: io.airlift.command.ParseArgumentsMissingException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
```
Other than that, everything appears to be working great.  Once we put or data back into Cassandra and start using the elastic search, I'll let you know how everything goes and if we run into any other errors.
For the record, this was a fresh install on an AWS instance running Ubuntu 16.

**Comment by DBarthe** [comment]
Yes we had this problem too, but we fix today only.

I uploaded a new deb: [https://expirebox.com/download/8a79c8aec9b9beae07b3040b44e7f194.html](https://expirebox.com/download/8a79c8aec9b9beae07b3040b44e7f194.html)
(sha1sum fe158b10a393f8384fb35ee6830432d49a40b846)

Simply run the same command over the new file:
```bash
sudo dpkg -i elassandra-2.4.2-SNAPSHOT_all.deb
```
This will add the missing library and restart elassandra, while keeping your configuration and data unchanged.

Otherwise thanks for feedback :)

**Comment by SympleSynz** [comment]
Hi @DBarthe 

From what we can tell so far, we haven't run into any major issues with the debian package.  Everything seemed very stable.  Ultimately, we had difficulty trying to find out how to create the elasticsearch mappings.  It may be a bug in the Cassandra version or the fact that we were running Cassandra on a single server and the replication was not kicking in. Overall, the package was good, we couldn't get it to work because of we didn't have an actual NetworkTopologyStrategy set up for Cassandra.  Thank you for all your help.

**Comment by DBarthe** [comment]
We provide deb and rpm packages. For instructions please refer to the [installation documentation](http://elassandra.readthedocs.io/en/latest/installation.html#deb-package).
