### ISSUE TITLE
It would be valuable to document the practical benefit of Elassandra over Elasticsearch

### ISSUE THREAD

**Issue by yehosef** [strapdata/elassandra#133]
Traditionally one of the big values of Cassandra over Elasticsearch (ES) was is reliability whereas ES was known to lose data it certain situations.  Or it's ability to scale linearly with new nodes.

Many of these problems have been solved or improved in newer versions of ES (>5).  

It would be valuable to document somewhere what benefit I'm going to experience by using Elessandra (EL)  over ES.  Eg, in these failure situations, EL does not lose data whereas ES does.  Or, EL can index/search/update X docs/sec and ES can only do Y.

In my mind, having two good products merged into one doesn't automatically make it better - did I inherit the benefits of both or the faults of both (or even more faults..)

**Comment by vroyer** [comment]
Here a brief response that could be added to the doc :
-Elassandra is masterless, while elasticsearch master node is a SPOF.
-Elassandra is a shared multi-master database, where Elasticsearch (and also Mongoldb or CouchBase) are shared master-slave. This means that Elassandra has no Single Point Of Write, helping to achieve high availability.
-Elassandra relies on Cassandra to store data, a column store, where Elasticsearch (and also Mongoldb, CouchBase) are document stores. Managing concurrent update on many datacenters can be tricky with document stores, because merge based on Last Write Win of documents could lead to data loss, where Last Write Win merge at the column level allows finer granularity.
-Elassandra inherits Cassandra data repair mechanisms (hinted handoff, read repair and nodetool repair) allowing to support cross datacenter replication. Elasticsearch has no incremental repair mechanism.
-Elassandra scale by adding more nodes with an automatic resharding where only data pulled from existing nodes are re-indexed. With elasticsearch, when # nodes = #shards, adding more node involve a full index rebuild.

Hope this helps.
Thanks.

**Comment by vroyer** [comment]
New improved README.
