### ISSUE TITLE
Cassandra PK and performace

### ISSUE THREAD

**Issue by jluzny** [strapdata/elassandra#140]
Is there any recommendation how Cassandra primary keys should be defined to achieve the best performance in Elassandra when querying via ES layer? 
Is there any performance penalty when using complex compound keys (e.g. one partition + 3 clustering keys) vs. having just one primary (partition) UUID key?

Thanks.

**Comment by vroyer** [comment]
There is a small cost to parse a JSON array rather than a String into a C* primary key, but the major concern is length and randomness of your PK.
As explain in http://blog.mikemccandless.com/2014/05/choosing-fast-unique-identifier-uuid.html <http://blog.mikemccandless.com/2014/05/choosing-fast-unique-identifier-uuid.html> , random _id is the worst choice, so avoid random key in your C* PK, and keep-it reasonably small.
> one partition + 3 clustering keys
>
