### ISSUE TITLE
upgrading from 2.4.5.6 to 5.5.0.8

### ISSUE THREAD

**Issue by devnut** [strapdata/elassandra#144]
Hello,

For some reason when upgrading from 2.4.5.6 to 5.5.0.8 we're getting indexes being rebuilt from scratch.   According to everything I'm reading the indexes between these version on ElasticSearch are compatible.  Is it expected that we'd have this situation?

After upgrading the binary and restarting, this is what I see in the log file that might be relevant:

```
2017-12-05 20:27:27,772 WARN  [main] IndexFolderUpgrader.java:117 upgrade [/var/lib/cassandra/elasticsearch.data/Test/nodes/0/indices/dev] no index state found - ignoring
```

then a bit later

```
2017-12-05 20:27:29,942 DEBUG [elasticsearch[172.30.64.21][clusterService#updateTask][T#1]] CassandraShardStartedBarrier.java:91 isReadyToIndex readyToIndex=true latch=0 state=cluster uuid: 9d0e8942-20dd-4bb8-878d-f20b4e847d8f
-- index [[dev/sPlYCICUSf-J8dt6DLsAXA]]
```

We have a very large index in production, so re-indexing it if its not necessary seems pretty painful.

Thanks!

- Greg

**Comment by vroyer** [comment]
Hi,

Standard Elasticsearch upgrade from 2.4 to 5.5 would require a full cluster stop+start because of changes in the elasticsearch transport inter node protocol.
However, ES 5.5 can read 2.4 indices coming from a snapshot + restore. 

With Elassandra, each elasticsearch enabled datacenter requires a full stop+restart for upgrade for the same reason as standard elasticsearch (transport protocol changes).
Lucene 6.6 introduced more efficient  numeric range query used by elassandra to avoid duplicate results when searching. Search can be up to 5 times faster.
So, we didn’t event test if elassandra could run 2.4 indices in version 5.5.+, you have to rebuild from SSTables.

If you want to rebuild indices quickly, use a nodetool rebuild_index —threads <X> <ks> <table> elastic_<table>_idx on every nodes.
(You will need to stop current rebuild automatically started when creating an index on existing data, with nodetool stop —compaction-id <uuid>)

Thanks,
Vincent.

**Comment by devnut** [comment]
This is a very large cluster.  My hope would have been that 5.5 would be able to read 2.4 while we rebuilt the new index after bringing it back up before doing the drop/rename of the indices that we would normally do in a case like this.

Sounds like this isn't going to be an option.

- Greg

**Comment by vroyer** [comment]
Another option it to temporary create a new C* datacenter with elassandra 5.5, creates  the new mapping, rebuild all nodes from the source datacenter, then switch from the datacenter running elassandra 2.4 to the new one in elassandra 5.5, and finally release the old one.
There is no downtime with this scenario.

**Comment by devnut** [comment]
Yeah I was thinking of that too but isn’t there an issue with elastic_admin.metadata being replicated since it’s format has changed so much?

**Comment by vroyer** [comment]
By default, all datacenters share the same mapping in elastic_admin.metadata, but as explained in the [documentation](http://doc.elassandra.io/en/latest/configuration.html#multi-datacenter-configuration), you could have distinct mappings for each elassandra version (a 2.4 mapping in datacenter 1, a 5.5 mapping in datacenter 2). And this allows you to softly migrates by testing new Elassandra version before stopping the old one.
