### ISSUE TITLE
snapshot path

### ISSUE THREAD

**Issue by afrozl** [strapdata/elassandra#150]
I apologize if this is not the appropriate forum for these types of questions, but I am unable to find the relevant info in the docs. I am attempting to create a snapshot repository but haven't had much luck. I can create the repository, but  am unable to create snapshots. I suspect it has to do with the path.repo setting in the elasticsearch.yml file but am unable to verify if this is indeed being read/used. I can create the repo, but cannot query the repository:

<pre>
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "request [/_snapshot/primary_repo/_all] contains unrecognized parameter: [repository]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "request [/_snapshot/primary_repo/_all] contains unrecognized parameter: [repository]"
  },
  "status": 400
}
</pre>

Perhaps I have something mis-configured? What is the recommended method of transferring data from an existing ES cluster?

Thanks

**Comment by afrozl** [comment]
I found this, which explains the inability to snapshot:

```

Elasticsearch unsupported features
----------------------------------

* Tribe node allows to query multiple Elasticsearch clusters. This feature is not currently supported by Elassandra.
* Elasticsearch snapshot and restore operations are disabled (See Elassandra backup and restore in operations).

```

Is there a technical reason for disabling  snapshots? It would seem to reduce interoperability with elasticsearch quite a bit.

**Comment by vroyer** [comment]
Elassandra does not support elasticsearch snapshot because it requires a shared FS and because of elassandra data distribution (one shard per node per index in elassandra, vs. X shards with some replica in elasticsearch). Instead, you can do cassandra snapshot including elasticsearch files as explained in the [elassandra doc](http://doc.elassandra.io/en/latest/operations.html#backup-and-restore). 

If you want to move your data from elasticsearch to elassandra, you can use logstash with the elasticsearch input plugin + the elasticsearch or cassandra output plugin (the cassandra output plugin will be faster because the CQL directly send data to the right node).

Thanks.

**Comment by afrozl** [comment]
Makes sense, although we do use snapshots with the google cloud storage plugin so a shared file system is not needed.

Nevertheless, elassandra is very attractive since we maintain separate clusters of cassandra and elasticsearch and it would be nice to consolidate.

I'll keep working with it to see if it meets our needs. Some of the hiccups I've hit so far gave to do with empty/null objects. I built and installed the fixed version and that helped, but its still picky in terms of handling nulls since elasticsearch doesn't consider an empty array as a null.  I also notice that I'm hitting different errors when indexing via the bulk API vs a PU. Documents that error out with the bulk API go through fine with a PUT. Is that expected behavior?

Thanks

**Comment by vroyer** [comment]
If you have unexpected error, please open a case with the detailed information.
BTW, i would recommend to use the CQL driver to ingest data rather than the ES bulk API, because cassandra is just better for write operation (no JSON overhead + write on the right node according to the primary key, asynchronous write, batch etc...).

**Comment by afrozl** [comment]
Thanks for the direction. I'll do some semi-formal tests and open an issue when I have specific details. 

As for using the CQL driver for ingestion, I'm not sure that would be more efficient since our source documents are in JSON format?
