### ISSUE TITLE
Excludes from _source ignored

### ISSUE THREAD

**Issue by AlbericMartel** [strapdata/elassandra#151]
**Elassandra version**: 5.5.0.9

**OS version**: Ubuntu 16.04.3 LTS

**Description of the problem including expected versus actual behavior**:
I am using the docker image of Elassandra 5.5.0.9. 
When I execute a request in Elassandra, I don't want to get the whole _source. So when creating my index I specified in my mapping :
"_source": {
  "enabled":true,
  "excludes" : [
    "field2"
  ]
}

However, in Cassandra, when indexing a document, the _source column is created and populated but excludes is ignored which is inconsistent with Elasticsearch behavior.

**index mapping
{
	"mappings" : {
		"type1" : {
			"_source": {
				"enabled":true,
				"excludes" : [
					"field2"
				]
			},
		    "properties" : {
			"field1" : { 
				"type" : "text"
			},
			"field2" : { 
				"type" : "text"
			}
        }
}

**document inserted
{
	"field1":"value1",
	"field2":"value2"
}

**Querying cassandra
select blobAsText("_source") from type1;

 system.blobastext(_source)
---------------------------------------------------------------------------------------------------------------
 {\n\t"field1":"value1",\n\t"field2":"value2"\n}

**Comment by vroyer** [comment]
Hi,
In elassandra, _source is disable by default, meaning that elasticsearch don't keep the _source because it's all fields are stored in cassandra. By enabling _source, you say that you want store the _source in a dedicated blob "_source" column. This is intended to store geoshape.

The elassandra philosophie is to use cassandra as a primary data store, and then, indexing a field not stored in cassandra is not possible.
Regards.
Vincent.
