### ISSUE TITLE
Performance between Elassandra and native Cassandra

### ISSUE THREAD

**Issue by toluaina** [strapdata/elassandra#155]
Hello,

I have been running some benchmarks with the latest version of elassandra 5.5.0.9.
I am getting consistent speed of 1028.25 writes per seconds.

I have run the same test against a native Cassandra installation and got
2724.08+ writes per second. 

I noticed when I drop/delete the custom database index created for the elasticsearch in Cassandra (org.elassandra.index.ExtendedElasticSecondaryIndex)  that I get the same write speed of a native Cassandra installation.

Any ideas about the difference in performance?
Any help or advice would be greatly appreciated. 
I can provide more info if necessary

regards,

**Comment by vroyer** [comment]
Hi,

Elassandra synchronously generates elasticsearch lucene files on disk when writing in an indexed C* table.
Of course, this involve a CPU+IO overhead, but you will then be able to search with the elasticsearch API in your C* tables.
You can fine tune this by splitting SSTables and Lucene files on separate disks, you may increase the number of writer threads if not already overloaded.

You can also reduce elasticsearch overhead by limiting the number of indexed columns, disable the _all field if to needed, and set the refresh interval to 5m or more to avoid useless refresh (default is every second) as shown bellow.

curl -XPUT "$NODE:9200/myindex" -d'{ 
        "settings": { "index.refresh_interval" : "5m",
                      "_all": { "enabled": false }
         }
}'

Regards,
Vincent.

**Comment by toluaina** [comment]
Hello,
Thanks for your response.
A quick question. Is it possible to restrict writes to elastic search. So that the operating model is read from elastic search and writing to Cassandra. Without enabling xpack.

Thanks

Tolu

On 16 Jan 2018 11:52 pm, "Vincent Royer" <notifications@github.com<mailto:notifications@github.com>> wrote:
Hi,

Elassandra synchronously generates elasticsearch lucene files on disk when writing in an indexed C* table.
Of course, this involve a CPU+IO overhead, but you will then be able to search with the elasticsearch API in your C* tables.
You can fine tune this by splitting SSTables and Lucene files on separate disks, you may increase the number of writer threads if not already overloaded.

You can also reduce elasticsearch overhead by limiting the number of indexed columns, disable the _all field if to needed, and set the refresh interval to 5m or more to avoid useless refresh (default is every second) as shown bellow.

curl -XPUT "$NODE:9200/myindex" -d'{
"settings": { "index.refresh_interval" : "5m",
"_all": { "enabled": false }
}
}'

Regards,
Vincent.

**Comment by joshuabuildsthings** [comment]
If there are performance concerns, it might be worth exploring how compatible Elassandra is with ScyllaDB. ScyllaDB is wire-compatible with Cassandra, but was written from the ground up to provide higher performance.

**Comment by vroyer** [comment]
Cassandra is a row storage, and Elasticsearch an inverted index + a columnar storage.

So obviously, when indexing in elasticsearch, write is much more expensive, but you then get better search, sort and aggregation features with Elasticsearch. Because the elasticsearch _source is not more written in lucene, but in the underlying cassandra table, the total cost of a write is the cassandra one, plus the elasticseach(lucene) one minus the elasticsearch _source document that would be written in the standard elasticsearch.

When writing in a cassandra table not indexed, performances are exactly the same as cassandra, because elassandra is just cassandra with a custom secondary index for indexed tables/columns.

This hybride storage allows you to setup the best storage depending on your use case, and you get a simplier data pipeline.

Note that when indexing, cassandra columns are directly written as lucene fields, (there is no JSON generation+parsing overhead). And when requesting elasticsearch through the CQL cassandra driver (available in the Enterprise plugin), requested fields are directly sent in binary from cassandra, no JSON serialization/deserialization.

Finally, because ScyllaDB is written in C, integrating elasticsearch as custom secondary index is not so simple and would require a tricky java-C integration... (I'have already discuss that with ScyllaDB...)

**Comment by Remember2015** [comment]
> Cassandra is a row storage, and Elasticsearch an inverted index + a columnar storage.
> 
> So obviously, when indexing in elasticsearch, write is much more expensive, but you then get better search, sort and aggregation features with Elasticsearch. Because the elasticsearch _source is not more written in lucene, but in the underlying cassandra table, the total cost of a write is the cassandra one, plus the elasticseach(lucene) one minus the elasticsearch _source document that would be written in the standard elasticsearch.
> 
> When writing in a cassandra table not indexed, performances are exactly the same as cassandra, because elassandra is just cassandra with a custom secondary index for indexed tables/columns.
> 
> This hybride storage allows you to setup the best storage depending on your use case, and you get a simplier data pipeline.
> 
> Note that when indexing, cassandra columns are directly written as lucene fields, (there is no JSON generation+parsing overhead). And when requesting elasticsearch through the CQL cassandra driver (available in the Enterprise plugin), requested fields are directly sent in binary from cassandra, no JSON serialization/deserialization.
> 
> Finally, because ScyllaDB is written in C, integrating elasticsearch as custom secondary index is not so simple and would require a tricky java-C integration... (I'have already discuss that with ScyllaDB...)

So now is there any solution to integrate scylla and elasticsearch?

**Comment by vroyer** [comment]
Ask at scylla team ?

**Comment by silviucpp** [comment]
Hello @vroyer ,

In case I have a cassandra table with fields email, last_login_ts, last_login_ip and an ELS index on email, 
in case I do updates in cassandra like:

UPDATE users set last_login_ts = ?, last_login_ip = ? where email = ?

Will ELS bring any overhead (because the last_login_ts and last_login_ip are not indexed) ?

Silviu

**Comment by vroyer** [comment]
Hi,

I guess email is your primary key and you have some other indexed fields ?
So on every update, elassandra rebuild a document by reading indexed columns and index it in elasticsearch.
If indexed columns has no values in cassandra, it index an empty document in elasticsearch to keep the same semantic, with a small overhead in all cases. 

 - Vincent.

**Comment by silviucpp** [comment]
Hello,

So even if the non indexed columns are updated still elassandra needs to rebuild the document and reindex in elastic search on every update ?

Because both last_login_ts, last_login_ip are not indexed in elastic search. 

Silviu

**Comment by vroyer** [comment]
No, a Cassandra mutation with no indexed column is not indexed in elasticsearch (no read-before write). A C* mutation must contain at least one ES indexed column to trigger a read to build the elasticsearch document.
