### ISSUE TITLE
Search over a nested set returns wrong inner_hits

### ISSUE THREAD

**Issue by andre-paris** [strapdata/elassandra#161]
**Elasticsearch version**: 5.5.0.10

**Plugins installed**: []

**JVM version**: 1.8

Given the C* data:
```
CREATE TYPE IF NOT EXISTS model (
  name          VARCHAR,
  date          TIMESTAMP
);

CREATE TABLE IF NOT EXISTS make_models (
  make            VARCHAR,
  models          SET<FROZEN<model>>,
  PRIMARY KEY (make)
);

UPDATE make_models SET models = models + {{name : 'dart', date : '2018-01-29 11:53:00'}} WHERE make='dodge';
UPDATE make_models SET models = models + {{name : 'polara', date : '2018-01-29 11:54:00'}} WHERE make='dodge';
UPDATE make_models SET models = models + {{name : 'mustang', date : '2018-02-01 11:50:00'}} WHERE make='ford';
UPDATE make_models SET models = models + {{name : 'galaxie', date : '2018-02-01 11:51:00'}} WHERE make='ford';
UPDATE make_models SET models = models + {{name : 'camaro', date : '2018-02-01 12:50:00'}} WHERE make='gm';
UPDATE make_models SET models = models + {{name : 'chevelle', date : '2018-02-01 12:52:00'}} WHERE make='gm';
```
The ES mapping:
```
{
	"settings": {
		"keyspace": "test"
	},
	"mappings": {
		"make_models": {
			"_all": {
				"enabled": false
			},
			"_source": {
				"enabled": true
			},
			"discover": ".*"
		}
	}
}
```
When performing a POST /test/_search?pretty=true -d 
```
{
	"query": {
		"nested": {
			"path": "models",
			"query": {
				"term": {
					"models.name": "galaxie"
				}
			},
			"inner_hits": {}
		}
	}
}
```
The returned inner_hit is for "mustang" instead of "galaxie":
```
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.5404451,
    "hits" : [
      {
        "_index" : "teste.make",
        "_type" : "make_models",
        "_id" : "ford",
        "_score" : 1.5404451,
        "_source" : {
          "models" : [
            {
              "date" : "2018-02-01T13:51:00.000Z",
              "name" : "galaxie"
            },
            {
              "date" : "2018-02-01T13:50:00.000Z",
              "name" : "mustang"
            }
          ],
          "make" : "ford"
        },
        "inner_hits" : {
          "models" : {
            "hits" : {
              "total" : 1,
              "max_score" : 1.5404451,
              "hits" : [
                {
                  "_nested" : {
                    "field" : "models",
                    "offset" : 1
                  },
                  "_score" : 1.5404451,
                  "_source" : {
                    "date" : "2018-02-01T13:50:00.000Z",
                    "name" : "mustang"
                  }
                }
              ]
            }
          }
        }
      }
    ]
  }
}
```
This behavior is intermittent, for this example it's occurs only for 1 of the 6 entries in the table, and the entry change everytime I drops and recreates everything.
If I missing something, please let me know.

**Comment by vroyer** [comment]
Hi,

You should not enable _source, because in this case, it stores your document in a dedicated C* column not updated when you do a CQL update.
In the default configuration, Cassandra store your _source as a row in the underlying cassandra table and re-index it in elasticsearch on every update.

Regards,
Vincent.

**Comment by andre-paris** [comment]
Vincent,

Sorry, but I've tried with _"_source" : false_ on mapping and the problem persists.
Note that I'm not inserting (update) new data after creating de ES index...to reproduce, just follow the steps mentioned: 1st create the C* table and udt and insert the rows, then you create the ES index and do the search.

**Comment by andre-paris** [comment]
Just a hint: when change the column type from ```SET<FROZEN<model>>``` to ```LIST<FROZEN<model>>``` its works as expected.

**Comment by vroyer** [comment]
Hi,

I have reproduced and fix your issue.
A new release 5.5.0.11 is already available on the Release-Candidate repository [https://github.com/strapdata/elassandra5-rc/releases](https://github.com/strapdata/elassandra5-rc/releases).

Thanks for reporting the issue.
Vincent.

**Comment by andre-paris** [comment]
Vincent,

Thanks for the quick reply.
I'm glad to help.

Regards.

**Comment by andre-paris** [comment]
It's embarrassing but I've tested again with the RC and the problem is there.

Note: after creating the index via ES api, I had to run the nodetool rebuild_index command to index the data like this:
```
nodetool rebuild_index --threads <N> <keyspace_name> <table_name> elastic_<table_name>_idx
```

**Comment by vroyer** [comment]
Hi,

How did you reproduce the issue with the version 5.5.0.11 ?

nodetool rebuild_index only reindex SSTable, so if you have fresh data in the cassandra memtable, you should run a nodetool flush before.

Thanks.

**Comment by andre-paris** [comment]
Hi Vincent,

the same way as mentioned above (except for the flush):

1. create the C* udt ```model```, table ```make_models```, and execute the updates to insert the rows
1. as you suggested: ```nodetool flush```
1. create the ES index (source is disabled): ```PUT /test -d @mapping.json```
1. do the search: ```POST /test/_search -d @search.json```

Thank you

**Comment by vroyer** [comment]
Hi,

You should flush before creating the index, because creating the index involve a rebuild on flushed data.
Here is my results with the 5.5.0.11, all seems to work fine.

[cqlsh 5.0.1 | Cassandra 3.11.1.1-SNAPSHOT | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
cassandra@cqlsh> UPDATE test.make_models SET models = models + {{name : 'dart', date : '2018-01-29 11:53:00'}} WHERE make='dodge';
cassandra@cqlsh> UPDATE test.make_models SET models = models + {{name : 'polara', date : '2018-01-29 11:54:00'}} WHERE make='dodge';
cassandra@cqlsh> UPDATE test.make_models SET models = models + {{name : 'mustang', date : '2018-02-01 11:50:00'}} WHERE make='ford';
cassandra@cqlsh> UPDATE test.make_models SET models = models + {{name : 'galaxie', date : '2018-02-01 11:51:00'}} WHERE make='ford';
cassandra@cqlsh> UPDATE test.make_models SET models = models + {{name : 'camaro', date : '2018-02-01 12:50:00'}} WHERE make='gm';
cassandra@cqlsh> UPDATE test.make_models SET models = models + {{name : 'chevelle', date : '2018-02-01 12:52:00'}} WHERE make='gm';
cassandra@cqlsh> select * from test.make_models;

 make  | models
-------+--------------------------------------------------------------------------------------------------------------------------
    gm | {{name: 'camaro', date: '2018-02-01 11:50:00.000000+0000'}, {name: 'chevelle', date: '2018-02-01 11:52:00.000000+0000'}}
 dodge |     {{name: 'dart', date: '2018-01-29 10:53:00.000000+0000'}, {name: 'polara', date: '2018-01-29 10:54:00.000000+0000'}}
  ford | {{name: 'galaxie', date: '2018-02-01 10:51:00.000000+0000'}, {name: 'mustang', date: '2018-02-01 10:50:00.000000+0000'}}

(3 rows)


$ nodetool flush test
$ curl -XPUT $CREDENTIAL "https://$NODE:9200/test" -d'{
>     "settings": {
>         "keyspace": "test"
>     },
>     "mappings": {
>         "make_models": {
>             "discover": ".*"
>         }
>     }
> }'
{"acknowledged":true,"shards_acknowledged":true}

$ curl -XPOST $CREDENTIAL "https://$NODE:9200/test/_search?pretty=true" -d'{
>     "query": {
>         "nested": {
>             "path": "models",
>             "query": {
>                 "term": {
>                     "models.name": "galaxie"
>                 }
>             },
>             "inner_hits": {}
>         }
>     }
> }'
{
  "took" : 24,
  "timed_out" : false,
  "_shards" : {
    "total" : 2,
    "successful" : 2,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.2039728,
    "hits" : [
      {
        "_index" : "test",
        "_type" : "make_models",
        "_id" : "ford",
        "_score" : 1.2039728,
        "_source" : {
          "models" : [
            {
              "date" : "2018-02-01T10:50:00.000Z",
              "name" : "mustang"
            },
            {
              "date" : "2018-02-01T10:51:00.000Z",
              "name" : "galaxie"
            }
          ],
          "make" : "ford"
        },
        "inner_hits" : {
          "models" : {
            "hits" : {
              "total" : 1,
              "max_score" : 1.2039728,
              "hits" : [
                {
                  "_nested" : {
                    "field" : "models",
                    "offset" : 1
                  },
                  "_score" : 1.2039728,
                  "_source" : {
                    "date" : "2018-02-01T10:51:00.000Z",
                    "name" : "galaxie"
                  }
                }
              ]
            }
          }
        }
      }
    ]
  }
}

$ curl -XPOST $CREDENTIAL "https://$NODE:9200/test/_search?pretty=true" -d'{
>     "query": {
>         "nested": {
>             "path": "models",
>             "query": {
>                 "term": {
>                     "models.name": "mustang"
>                 }
>             },
>             "inner_hits": {}
>         }
>     }
> }'
{
  "took" : 27,
  "timed_out" : false,
  "_shards" : {
    "total" : 2,
    "successful" : 2,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.2039728,
    "hits" : [
      {
        "_index" : "test",
        "_type" : "make_models",
        "_id" : "ford",
        "_score" : 1.2039728,
        "_source" : {
          "models" : [
            {
              "date" : "2018-02-01T10:50:00.000Z",
              "name" : "mustang"
            },
            {
              "date" : "2018-02-01T10:51:00.000Z",
              "name" : "galaxie"
            }
          ],
          "make" : "ford"
        },
        "inner_hits" : {
          "models" : {
            "hits" : {
              "total" : 1,
              "max_score" : 1.2039728,
              "hits" : [
                {
                  "_nested" : {
                    "field" : "models",
                    "offset" : 0
                  },
                  "_score" : 1.2039728,
                  "_source" : {
                    "date" : "2018-02-01T10:50:00.000Z",
                    "name" : "mustang"
                  }
                }
              ]
            }
          }
        }
      }
    ]
  }
}

[cqlsh 5.0.1 | Cassandra 3.11.1.1-SNAPSHOT | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
cassandra@cqlsh> UPDATE test.make_models SET models = models + {{name : 'mustang', date : '2018-02-01 11:50:00'}} WHERE make='ford';
cassandra@cqlsh> exit

$ curl -XPOST $CREDENTIAL "https://$NODE:9200/test/_search?pretty=true" -d'{
>     "query": {
>         "nested": {
>             "path": "models",
>             "query": {
>                 "term": {
>                     "models.name": "galaxie"
>                 }
>             },
>             "inner_hits": {}
>         }
>     }
> }'
{
  "took" : 10,
  "timed_out" : false,
  "_shards" : {
    "total" : 2,
    "successful" : 2,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0296195,
    "hits" : [
      {
        "_index" : "test",
        "_type" : "make_models",
        "_id" : "ford",
        "_score" : 1.0296195,
        "_source" : {
          "models" : [
            {
              "date" : "2018-02-01T10:50:00.000Z",
              "name" : "mustang"
            },
            {
              "date" : "2018-02-01T10:51:00.000Z",
              "name" : "galaxie"
            }
          ],
          "make" : "ford"
        },
        "inner_hits" : {
          "models" : {
            "hits" : {
              "total" : 1,
              "max_score" : 1.0296195,
              "hits" : [
                {
                  "_nested" : {
                    "field" : "models",
                    "offset" : 1
                  },
                  "_score" : 1.0296195,
                  "_source" : {
                    "date" : "2018-02-01T10:51:00.000Z",
                    "name" : "galaxie"
                  }
                }
              ]
            }
          }
        }
      }
    ]
  }
}

**Comment by spendyala** [comment]
I am seeing this issue my nested queries 

```
CREATE TYPE db.data_json_type (
    created_date timestamp,
    user_name_id text,
    updated_date timestamp,
    expires_date timestamp
);

CREATE TABLE db.table_1 (
    load_date timestamp,
    data_json frozen<data_json_type>,
    source text,
    date timestamp
)

With the elasticsearch query

curl -XPOST 'http://localhost:9200/db/table/_search?size=10&pretty' -d '{
    "query": {
        "filtered": {
            "query": {
                "term": {
                    "user_name_id": "<email_address>"
                }
            },
            "filter": {
                "nested": {
                    "path": "data_json",
                    "filter": {
                        "term": {
                            "created_date": "2018-03-012T00:00:00.000Z"
                        }
                    }
                }
            }
        }
    }
}'
```

I see results of users that were created in 2016, 2017, sometimes even 2010 records.
