### ISSUE TITLE
Windows installation ?

### ISSUE THREAD

**Issue by Phil4** [strapdata/elassandra#18]
I tried to install the tool but I'm using Windows as operating system.
Everything seems to be working except that no Elastic Search instance is launched.
I think it is only launched through _bin/cassandra_ but not from _bin/cassandra.bat_ but I didn't look further.

Here is the trace of the command "_cassandra -e_":

<pre>
WARNING! Powershell script execution unavailable.
   Please use 'powershell Set-ExecutionPolicy Unrestricted'
   on this user-account to run cassandra with fully featured
   functionality on this platform.
Starting with legacy startup options
Starting Cassandra Server
</pre>

**Comment by vroyer** [comment]
Sorry, the cassandra.bat is not ready to run elassandra on Windows right now. However, you can probably copy the code of the -e option from bin/cassandra to the bin/cassandra.bat to activate Elasticsearch on your windows plateform. 
Thanks',
Vincent.

**Comment by ddorian** [comment]
@vroyer 
I downloaded cassandra-2.2.6, then loaded elassandra-2.1.1-14 on top of it, and only changed the classpath/CASSANDRA_MAIN

`CASSANDRA_MAIN=org.apache.cassandra.service.ElassandraDaemon`

But it errors with "could not find or load main class org.apache.cassandra.service.ElassandraDaemon. 

Any idea ?
Thank You

**Comment by ddorian** [comment]
@vroyer I fixed the previous issue by redownloading the release.

Though now I'm getting: 

Starting with legacy startup options
Starting Cassandra Server
{2.1.1}: Initialization Failed ...
- IllegalStateException[failed to load bundle [] due to jar hell]
      NoSuchFileException[C:\Users\admin\Desktop\elassandra-2.1.1-14\build\cla
  sses\main]

**Comment by vroyer** [comment]
Hi,
This is a classpath issue. org.apache.cassandra.service.ElassandraDaemon is the main class to launch Elassandra, but it seems that C:\Users\admin\Desktop\elassandra-2.1.1-14\build\cla sses\main does not contains it.
Thanks.

**Comment by ddorian** [comment]
@vroyer 

I fixed that issue, about ElassandraDaemon. See my earlier message.

**Comment by ddorian** [comment]
@vroyer 
This happens when I run it on ubuntu12.04:

Starting with Elasticsearch enabled.
CompilerOracle: inline org/apache/cassandra/db/AbstractNativeCell.compareTo (Lorg/apache/cassandra/db/composites/Composite;)I
CompilerOracle: inline org/apache/cassandra/db/composites/AbstractSimpleCellNameType.compareUnsigned (Lorg/apache/cassandra/db/composites/Composite;Lorg/apache/cassandra/db/composites/Composite;)I
CompilerOracle: inline org/apache/cassandra/io/util/Memory.checkBounds (JJ)V
CompilerOracle: inline org/apache/cassandra/io/util/SafeMemory.checkBounds (JJ)V
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compare (Ljava/nio/ByteBuffer;[B)I
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compare ([BLjava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compareUnsigned (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/lang/Object;JILjava/lang/Object;JI)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/lang/Object;JILjava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
22:01:09.840 [main] WARN  org.elasticsearch.bootstrap - jvm uses the client vm, make sure to run `java` with the server vm for best performance by adding `-server` to the command line
22:01:12.776 [main] ERROR o.e.o.a.c.service.ElassandraDaemon - Exception
java.lang.ExceptionInInitializerError: null
    at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:124) ~[elassandra-2.1.1-14.jar:na]
    at org.apache.cassandra.service.ClientState.<clinit>(ClientState.java:70) ~[elassandra-2.1.1-14.jar:na]
    at org.apache.cassandra.cql3.QueryProcessor$InternalStateInstance.<init>(QueryProcessor.java:153) ~[elassandra-2.1.1-14.jar:na]
    at org.apache.cassandra.cql3.QueryProcessor$InternalStateInstance.<clinit>(QueryProcessor.java:147) ~[elassandra-2.1.1-14.jar:na]
    at org.apache.cassandra.cql3.QueryProcessor.internalQueryState(QueryProcessor.java:161) ~[elassandra-2.1.1-14.jar:na]
    at org.apache.cassandra.cql3.QueryProcessor.executeOnceInternal(QueryProcessor.java:334) ~[elassandra-2.1.1-14.jar:na]
    at org.apache.cassandra.service.ElassandraDaemon.activate(ElassandraDaemon.java:104) ~[elassandra-2.1.1-14.jar:na]
    at org.apache.cassandra.service.ElassandraDaemon.main(ElassandraDaemon.java:347) ~[elassandra-2.1.1-14.jar:na]
Caused by: org.apache.cassandra.exceptions.ConfigurationException: Expecting URI in variable: [cassandra.config].  Please prefix the file with file:/// for local files or file://<server>/ for remote files. Aborting. If you are executing this from an external tool, it needs to set Config.setClientMode(true) to avoid loading configuration.
    at org.apache.cassandra.config.YamlConfigurationLoader.getStorageConfigURL(YamlConfigurationLoader.java:73) ~[elassandra-2.1.1-14.jar:na]
    at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:85) ~[elassandra-2.1.1-14.jar:na]
    at org.apache.cassandra.config.DatabaseDescriptor.loadConfig(DatabaseDescriptor.java:135) ~[elassandra-2.1.1-14.jar:na]
    at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:119) ~[elassandra-2.1.1-14.jar:na]
    ... 7 common frames omitted

**Comment by vroyer** [comment]
See Caused by: org.apache.cassandra.exceptions.ConfigurationException: Expecting URI in variable: [cassandra.config]. Please prefix the file with file:/// for local files or file:/// for remote files. 
You should set CASSANDRA_CONF env variable or cassandra.config system property.

You may try to install the debian package available at http://packages.elassandra.io/deb/elassandra_2.1.1-14_all.deb

**Comment by ddorian** [comment]
@vroyer 
Another error trying to manually install the .deb file.

![virtualbox_ubuntu 14 04 server 32bit _06_07_2016_11_12_57](https://cloud.githubusercontent.com/assets/1592898/16613390/1e598a3e-436c-11e6-8c1f-9f4e184e9a1f.png)

**Comment by ddorian** [comment]
Even this guide doesn't work with error:

![virtualbox_ubuntu 14 04 server 32bit _06_07_2016_13_39_19](https://cloud.githubusercontent.com/assets/1592898/16616690/158ecc9e-437f-11e6-881b-0c27fffb7e84.png)

Somehow it's getting the path wrong.

**Comment by vroyer** [comment]
Please use the rigth path i gave you yesterday 
http://packages.elassandra.io/deb/elassandra_2.1.1-14_all.deb

**Comment by ddorian** [comment]
@vroyer As you can see [here ](https://github.com/vroyer/elassandra/issues/18#issuecomment-230722334) I have downloaded the right file. 
While when using apt-get it uses the wrong path.

**Comment by ddorian** [comment]
@vroyer can you give me sample of cassandra.config value (absolute path) that I can use or environment variable value? I tried different options and none worked and also tried searching for samples and couldn't find any. thanks

**Comment by vroyer** [comment]
Hi,
We are checking that the packages 2.1.1-14 is correct.
In order to start elassandra, you should set and export CASSANDRA_HOME to your elassandra installation directory.
Thanks',
Vincent.

**Comment by dukei** [comment]
@vroyer , I have managed to patch cassandra.ps1 and set CASSANDRA_MAIN to ElassandraDaemon. Still the elassandra does not load with the following error:

{2.4.2}: Initialization Failed ...
- IllegalStateException[failed to load bundle [file:/C:/elassandra-2.4.2/modules/lang-expression/antlr4-runtime-4.5.1-1.jar, file:/C:/elassandra-2.4.2/modules/lang-expression/asm-commons-5.0.4.jar, file:/C:/elassandra-2.4.2/modules/lang-expression/lang-expression-2.4.2.jar, file:/C:/elassandra-2.4.2/modules/lang-expression/lucene-expressions-5.5.2.jar] due to jar hell]
        NoSuchFileException[C:\elassandra-2.4.2\build\classes\main]

C:\elassandra-2.4.2\build\classes\main does not exist at all, it is development folder in a class path and I am trying to launch elassandra from a tarball.

How can I start elassandra on windows?

**Comment by dukei** [comment]
Well it has started sucessfully when I created these build directories.

I have modified windows launch scripts:
https://github.com/strapdata/elassandra/pull/97

**Comment by DBarthe** [comment]
Windows support added with 779289e6ee1043bae771a2981108b3f2b8156d2d

**Comment by jsebrien** [comment]
The previous commit does not seem to be merged in 6.x version. How can we start Elassandra under windows?
