### ISSUE TITLE
java.lang.NullPointerException when starting elassandra

### ISSUE THREAD

**Issue by justinjoseph89** [strapdata/elassandra#19]
Hi,
while starting elassandra using,
`./cassandra -e`
i got an error in system.log

> 2016-05-19 18:58:09,525 ERROR [main] ElassandraDaemon.java:376 main Exception
> java.lang.NullPointerException: null
>         at org.apache.cassandra.service.ElassandraDaemon.activate(ElassandraDaemon.java:112) ~[elassandra-2.1.1-10.jar:na]
>         at org.apache.cassandra.service.ElassandraDaemon.main(ElassandraDaemon.java:338) ~[elassandra-2.1.1-10.jar:na]

What will be the reason ? Is there any need for another elasticsearch server?

**Comment by vroyer** [comment]
Hi,
Elasticsearch failed to initialize, you probably have an error or a warning message in your system.log before that error. Could you set you debug level to TRACE in conf/logback.xml, restart and attach your log/system.log file to this issue ?
Thanks,
Vincent

**Comment by justinjoseph89** [comment]
Hi,
Please find the system.log,
[see this](https://github.com/justinjoseph89/logfile/blob/master/system.txt)
Thanks,
Justin

**Comment by vroyer** [comment]
Hi,

Thanks for your logs.
I think you are using the CassandraDeamon class provided with Cassandra, not the one provided with Elassandra ?
The CassandraDeamon class provided with Elassandra includes 3 lines of code to enhance the boot sequence in order to start elasticsearch at the right time.

BTW, Elassandra-2.1.1-x.jar includes all required classes from cassandra and elasticsearch, so you don't need to add any jar to the elassandra tarball.

If you have built from source, check the shade task where the followings classes are excluded form the original cassandra-all.jar and overwritten by the one provided by elassandra.
<filter>
    <artifact>org.apache.cassandra:cassandra-all</artifact>
    <excludes>
                <exclude>org/apache/cassandra/cql3/QueryOptions_.class</exclude>
                <exclude>org/apache/cassandra/cql3/UntypedResultSet_.class</exclude>
                <exclude>org/apache/cassandra/cql3/statements/CreateIndexStatement_.class</exclude>
                <exclude>org/apache/cassandra/service/CassandraDaemon_.class</exclude>
                <exclude>org/apache/cassandra/service/StorageService$_.class</exclude>
                <exclude>org/apache/cassandra/service/StorageService.class</exclude>
                <exclude>org/apache/cassandra/db/index/SecondaryIndexManager_.class</exclude>
        </excludes>
</filter>

I have set an explicit error message if this happen again for the next elassandra release.

Thanks,
Vincent.
