### ISSUE TITLE
Memory lock not working

### ISSUE THREAD

**Issue by Gappa88** [strapdata/elassandra#202]
I'm using Elassandra-6.2.3.1. 

I can't enable **memory lock** as it is possible in Elasticsearch 5.x/6.x. 
I followed Elassandra docs [https://elassandra.readthedocs.io/en/latest/configuration.html#sizing-and-tunning](url) turning swap off and setting Xms and Xmx but 
```
GET _nodes?filter_path=**.mlockall
{
  "nodes": {
    "c5a17dbd-40ef-4f58-b132-0d977a92f1a1": {
      "process": {
        "mlockall": false
      }
    },
    "f088d009-bd97-4e35-9f20-60006a68b363": {
      "process": {
        "mlockall": false
      }
    },
    "e82191ad-9d9f-459f-9da0-2b0457ad6611": {
      "process": {
        "mlockall": false
      }
    }
  }
}
```
Is there a way to enable memory lock or Elassandra implicity already has this feature?

**Comment by vroyer** [comment]
If logging is INFO for org.apache.cassandra.utils.NativeLibrary, you should have the following message in your logs indicating that mlockall is enabled:

`2018-06-18 18:22:35,894 INFO  [main] NativeLibrary.java:174 tryMlockall JNA mlockall successful`

Unfortunately, the information reported by _node is wrong because initialized before the cassandra JNA setup. This is now fixed in https://github.com/strapdata/elassandra/commit/52535765e1965242d5d957d12774021dc819c81a

Thanks.

**Comment by Gappa88** [comment]
thank you @vroyer
