### ISSUE TITLE
 Is it possible to use another Cassandra ?

### ISSUE THREAD

**Issue by Prasanthmv** [strapdata/elassandra#21]
HI,
 Is it possible to use another Cassandra and replicate data to & from it . What all configurations i need to do if possible ?

**Comment by vroyer** [comment]
Hi,
Elassandra currently rely on cassandra 2.2.5. If you are running C\* 2.2.x, you can add an elassandra DC in you cluster and replicate with a nodetool rebuid. If you use 2.1 or 3.x, you'll need to copy your data between your cluster and a new one for elassandra.
Thanks'

**Comment by justinjoseph89** [comment]
@vroyer is there any way i can bring only the elasticsearch functionality into my existing Apache Cassandra?
Thanks,
Justin Joseph

**Comment by vroyer** [comment]
Hi Justin,
Elassandra includes a modified version of cassandra and elasticsearch. There is basically 2 options to bring elasticsearch to an existing cassandra cluster.
1-Build a new datacenter with elassandra and pull data from an existing datacenter as explained here https://docs.datastax.com/en/cassandra/2.1/cassandra/operations/ops_add_dc_to_cluster_t.html .
2-Stop all nodes of a datacenter and replace cassandra binaries by elassandra one, keeping your configuration and data files in place. Then start the main class ElassandraDaemon to start elasticsearch inside cassandra (option -e in the bin/cassandra provided with elassandra). Of course, you can still start cassandra only with elassandra binaries.

Elassandra is currently bound to cassandra 2.2.6, and of course, due to changes in the transport protocol, merging various major cassandra version in the same cluster could cause schema mismatch issue. For cassandra 2.1.x users who don't want to upgrade, we plan to release an elassandra bound to cassandra 2.1.14 (and later to cassandra 3.0). Let me know if you are running another version.

Thanks,
Vincent.

**Comment by justinjoseph89** [comment]
HI Vincent,
Thanks for the reply. Am looking forward to C*3.X release.
Thanks,
Justin

**Comment by RyanQuey** [comment]
Is there any update on this issue? Is it possible yet to use an Elassandra node together with a regular non-Elassandra C* node in one cluster, given that they are in different Datacenters for C* v.3.*?

For example, would it be possible to have a Datastax astra instance in the same cluster as an Elassandra node?

**Comment by vroyer** [comment]
A soon as all you nodes run the same major cassandra version (or cassandra compatible version), you should be able to run some Cassandra datacenters with Cassandra, and some other with Elassandra. FYI, there is no cross datacenters elasticsearch connection, each C* datacenter is an ES cluster. 

You just need to extract the class org.elassandra.index.ExtendedElasticSecondaryIndex from elassandra (in lib/elasticsearch-version.jar), and  add it in the Cassandra classpath to avoid ClassNotFoundException because this class is referenced in the CQL schema. For Datastax Astra, it should be possible if this class can be added to the classpath.
