### ISSUE TITLE
searching with routing ?

### ISSUE THREAD

**Issue by ddorian** [strapdata/elassandra#23]
Is it possible ? Maybe using a partition column ? Meaning how to only search 1 shard/node ?

**Comment by vroyer** [comment]
Hi,
Elasticsearch routing becomes meaningless in elassandra, document are located on cassandra node depending on their partition key. If you create a type mapping with elasticsearch, primary key will be a string column name _id.  You can also create a cassandra table with a compound primary key, then index it with the following command.

curl -XPUT "http://$NODE:9200/<keyspace>/_mapping/<table>" -d '{ "<table>" : { "columns_regexp" : ".*" }}'

Documents will be distributed according to the partition key and elasticsearch _id will be a string representation of a JSON array of your compound primary key.

**Comment by ddorian** [comment]
I understand that, but how can I make sure to only hit 1(or several) node(s) when I do a search ? (what _routing does)

In this case, I know the partition-key(s), but can I use them to restrict search to 1 or several nodes ?

**Comment by vroyer** [comment]
With elassandra, you don't care about routing anymore, routing is automatic when indexing or getting a document (get is in fact a CQL SELECT <fields> FROM <table> WHERE "_id" = <id>). Because the partition key is included in _id when indexing, _id uniqueness is guaranteed across the cluster (as the cassandra primary key).

**Comment by ddorian** [comment]
I understand in those cases, but you didn't mention "search", only crud.
Say I have a table with "partition=user_id". How can I do an es-search to only hit the node where user_id=5 ?

**Comment by vroyer** [comment]
Currently, elassandra does not restrict search on a node hosting the partition key. The search result is OK because of uniquness of _id, but as you suggest, restricting the search to a node hosting the partition key (_routing converted to a token) could improve the overall performance.  I keep this for the next release.
Thanks.

**Comment by ddorian** [comment]
By reading the docs here on _routing: it seems this is fixed, right ?
http://doc.elassandra.io/en/latest/mapping.html#meta-fields
