### ISSUE TITLE
Plans to support ES 6.5?

### ISSUE THREAD

**Issue by laran** [strapdata/elassandra#240]
What plans are there to support the latest version (6.5.0 right now) of Elasticsearch?

**Comment by vroyer** [comment]
Yes, this is on the roadmap.

**Comment by ltfi** [comment]
Looking forward to hearing from you 👍

**Comment by laran** [comment]
Is it written down anywhere what’s involved in the upgrade? I’m curious if I might be able to help.

**Comment by DBarthe** [comment]
Hi @Laran,

Basically it implies :
* rebasing elassandra commits on top of elasticsearch v6.5.x branch. It
should be relatively straightforward since it's a minor upgrade
* resolving dependency version conflicts between elasticsearch and cassandra
* doing a lot of testing


Le mer. 28 nov. 2018 à 08:17, Laran Evans <notifications@github.com> a
écrit :

**Comment by ltfi** [comment]
@vroyer Could you share your roadmap with us, when is this update scheduled (if is scheduled) ?

**Comment by berniemoran** [comment]
Any news on support for elasticsearch 6.5x or the process involved in integrating it?

**Comment by vroyer** [comment]
Development is on going to directly switch from 6.2 to elasticsearch version 7.2+

**Comment by vroyer** [comment]
Elassandra 6.8.4.0 = Cassandra 3.11.5 + Elasticsearch 6.8.4 is out !
