### ISSUE TITLE
Hardware sizing calculation [Question]

### ISSUE THREAD

**Issue by m1sta** [strapdata/elassandra#27]
Has elassandra been tested at scale? Are you able to provide any guidance to help calculate hardware requirements based on data set sizes?

**Comment by vroyer** [comment]
Hi,
You should have at least 32Gb per node, and configured elassandra with half the total RAM up to maximum of 30,5Gb. But if you are not aggregating on analyzed string fields, you can probably use less memory to improve file system cache.

For write, elassandra write throughput is roughly half the throughput of cassandra if you index all columns. In this scenario, Cassandra and Elasticsearch files with be roughly the same size, for example 100Gb of cassandra data generates 100Gb of elasticsearch index files if you map all columns, but again, write throughput and elasticsearch disk usage will depend on your elasticsearch mapping.

In your cassandra schema, avoid huge indexed wide rows, because locking on wide rows can dramatically affect write performance.

For good search performance, keep shards under 50Gb each, and use partitioned index to split a cassandra table to more than one shard per node, see http://doc.elassandra.io/en/latest/mapping.html#partitioned-index.

Finally, depending on your hardware, you should have a few Tb of data per node and add more nodes to improve performances (index/search throughput) and/or increase the volume of data. Keep in mind that elassandra should require less nodes than  separate elasticsearch + cassandra nodes providing the same service.

Thanks',
Vincent

**Comment by ddorian** [comment]
@vroyer 

Why do you say less nodes compared to cassandra + elasticsearch (assuming you don't store "_source" in elasticsearch) ? Or is that by lowering per-shard overhead since you can include everything in 1 shard while in normal-es you have to over provision the number of shards.

**Comment by RayWhitmer** [comment]
"For write, elassandra write throughput is roughly half the throughput of cassandra if you index all columns."

It would be nice to be able to count on highly-optimized Cassandra write efficiency for significant operations on large data sets. Cassandra is UPSERT optimised, e.g. update a single property without reading the existing record. If a single property change is appended in Cassandra, then will Elassandra be smart enough to only reindex the one property, or will it reindex all properties for much less than half the throughput on single-property updates?

**Comment by ddorian** [comment]
@RayWhitmer it will reindex the full document.
