### ISSUE TITLE
Elasticsearch 6 single mapping-per-index

### ISSUE THREAD

**Issue by eonicle** [strapdata/elassandra#272]
Hello!

We are actively using Cassandra in production and would love to move to Elassandra, especially applications with complex queries, which are now using MongoDB. I tried playing with latest version of Elassandra (6.2.3.12) a bit, and found out there is a limitation to only [one mapping type in ES6](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/removal-of-types.html). This renders the whole concept of "index as keyspace, mapping type as table" not as useful as before. Should we use version 5 instead or follow ES guidelines to change app architecture to actually support only one mapping per namespace? For now this looks like all fields from tables will be kind of merged into one big table.
Thanks in advance!

**Comment by DBarthe** [comment]
Hello !
Since ES6, the concept of "index as keyspace" has changed, but fortunately this is not a problem since you can create one index per table.

I'll show you an example. Below, we create an index called `tweet-index` over the table `twitter.tweet`:
```
curl -XPUT -H 'Content-Type: application/json' "http://localhost:9200/tweet-index/" -d '{
   "settings" : { "keyspace" : "twitter" },
   "mappings" : {
      "tweet" : {
            "properties" : {
              "message" : { "type" : "text" },
              "post_date" : { "type" : "date", "format": "yyyy-MM-dd" },
              "user" : { "type" : "keyword" },
              "size" : { "type" : "long" }
            }
      }
   }
}
```

And then we create a second index called `user-index` over the table `twitter.user` : 
```
curl -XPUT -H 'Content-Type: application/json' "http://localhost:9200/user-index/" -d '{
   "settings" : { "keyspace" : "twitter" },
   "mappings" : {
      "user" : {
            "properties" : {
               "nickname" : { "type" : "keyword" }
            }
      }
   }
}
```
When creating the index, you can specify the underlying keyspace with ` "settings" : { "keyspace" : "keyspace_name" }`. This gives you the flexibility to create many indices per keyspace, for instance one per type you want to index.

Hope this helps!

**Comment by DBarthe** [comment]
Hello @eonicle, does my previous message answer to your question ?
