### ISSUE TITLE
Problem while installing

### ISSUE THREAD

**Issue by mddubey** [strapdata/elassandra#28]
Hi,
  I was trying to install Elassandra on centos using [this page](https://github.com/vroyer/elassandra/wiki/Install-Elassandra-with-RPM-%28CentOS,-RedHat,...%29#start-cassandra). I am facing few issues. I am using `CentOS release 6.5 (Final)`.

When I run command bellow
`yum install  elassandra`

It fails saying `Package elassandra-2.1.1-14.noarch.rpm is not signed`. Then I tried install with `--nogpgcheck`, and the installation completed.

When I try `su - esandra` it says `user esandra does not exist`.  I checked my /etc/passwd file and figured out there is a user named `cassandra".

using `cassandra` user I tried doing `systemctl start elassandra` it fails saying `systemctl, command not found`. 

Then I tried 

```

[cassandra@localhost ~]$ elassandra status
Elassandra is stopped.

[cassandra@localhost ~]$ elassandra start
Starting Elassandra: Password:
```

Have I missed anything while installation ?

Thanks

**Comment by xcourmont** [comment]
Hello,

The issue is by my side...
As elassandra relies  heavily on cassandra, and to be compliant with other tools, we decided to use user cassandra for elassandra...

I don't have test this rpm on centos 6, but I figure that you can start your elassandra instance with /opt/elassandra/bin/elassandra start as user cassandra.

I will remove the documentation that you pointed out and release a new one soon.

I will try to put a new rpm, tested in centos 6 this Week-End...

Regards

**Comment by nahtnam** [comment]
When I do `sudo yum install elassandra`, I get an error saying: `Failed to synchronize cache for repo 'Elassandra', disabling.` which makes it impossible for me to download.

**Comment by xcourmont** [comment]
Hello,

On which OS and version are you trying to install (CentOS, RHEL...) ?
Have you try sudo yum clean all --disablerepo=\* --enablerepo=Elassandra ?

Regards

**Comment by mddubey** [comment]
hey

 As I mentioned in my post, I was trying to install on centos 6.5. And I
followed the wiki page for centos(which has been removed now as mentioned
in your previous comment), which includes the command which you are
suggesting.

Thank You
Mritunjay

**Comment by xcourmont** [comment]
Sorry,

I was replying to nahtnam

Beside that, a lot of change had been made to the packages...
You should use this documentation instead : 

http://elassandra.readthedocs.io/en/latest/install_rpm.html

I just try to install it, and the repository is available...
This package has not been tested on CentOS 6.x, and it don't have init script (no support for chkconfig, service ... and so on).

I will try to support this as soon as possible, but it's better to use CentOS 7 

Feel free to post log messages, because it's hard to guess what is going wrong without it !!!

Regards

**Comment by mddubey** [comment]
hey,

I tried installing it, it's installed and running, but when I try to do cqlsh it gives me bellow error

```
[cassandra@localhost ~]$ cqlsh
Traceback (most recent call last):
  File "/opt/elassandra/bin/cqlsh.py", line 152, in <module>
    from cqlshlib import cql3handling, cqlhandling, pylexotron, sslhandling
ImportError: No module named cqlshlib
[cassandra@localhost ~]$

```

I am using centos 7.1

`CentOS Linux release 7.1.1503 (Core)`

**Comment by vroyer** [comment]
Hi,

Did you install the cassandra driver like this ?

pip install cassandra-driver

# from your elassandra instal directory.

python pylib/setup.py install

Thanks.

**Comment by MRYingLEE** [comment]
I have spent nearly 1 day to solve similar problem. The reason is that there is a mismatch between /usr/lib/python2.7/site-packages/ and  /usr/local/lib/python2.7/site-packages/ (for my specific folder tree). 

The command to use is as the following:

```
mv /usr/lib/python2.7/site-packages/* /usr/local/lib/python2.7/site-packages/
rmdir /usr/lib/python2.7/site-packages
ln -s /usr/local/lib/python2.7/site-packages /usr/lib/python2.7/site-packages
```

I guess you will find 2 /site-packages/ also.

Just for your reference.
