### ISSUE TITLE
Hybrid cluster/keyspace setup

### ISSUE THREAD

**Issue by thanigaiv** [strapdata/elassandra#30]
Is it possible to configure a particular keyspace (and its tables) with 2 datacenters where one DC is Cassandra-only nodes (serving realtime queries and no secondary index overhead) and second DC with Elassandra nodes (secondary indexes)?

**Comment by vroyer** [comment]
Yes, elassandra include cassandra 2.2.6, so you can start nodes with Elasticsearch enable (bin/cassandra -e) in one DC, or just cassandra (bin/cassandra) in another DC and replicate a keyspace between the two datacenters. However, you need to install and use the elassandra binaries on all nodes (because unfortunately, the cassandra NetworkTopologyStrategy cannot be subclass without a modification).
