### ISSUE TITLE
elastic_admin keyspace issues

### ISSUE THREAD

**Issue by palmert0147** [strapdata/elassandra#34]
Hi,

I installed Elassandra release 2.1.1-15 on Ubuntu 14.04 and ran into an issue with the elastic_admin keyspace failing to be created.  Is Elassandra supposed to work out of the box, or are there some other configuration settings I am missing?
[Here](https://github.com/vroyer/elassandra/files/360273/system.txt) is my log file regarding the startup and trying to index a twitter user.

Thanks

**Comment by vroyer** [comment]
Hi
It seems that there is no datacenter defined in your gossip property file sntich (see nullpointerexception in GossipPropertyFileSnitch.getDatacenter() . Could you check your cassandra configuration ?
Thanks',
Vincent.

**Comment by palmert0147** [comment]
Hi,
I am trying to get a single node instance running so I changed the endpoint_snitch to SimpleSnitch.  That got rid of the nullpointerexception in GossipPropertyFileSnitch.getDatacenter().  However there is still an error for the elasticadmin keyspace.  [Here ](https://github.com/vroyer/elassandra/files/366457/system1.txt)is the log file for the initial startup.

After killing the process and restarting there is not an issue with the keyspace.  I double checked that elastic_admin keyspace was created and it was.  When I went to try to index something it had a similar error.  [Here](https://github.com/vroyer/elassandra/files/366632/system2.txt) is the log file for the attempt at indexing.

Thanks

**Comment by vroyer** [comment]
The elastic_admin keyspace store the elasticsearch mapping in a table metadata. This keystore rely on a specific replication strategy, the DatacenterReplicationStrategy, which replicate on all node of the configured datacenter. Even if you succeeded to start, the paxos transaction used to update the elasticsearch mapping failed because DatacenterReplicationStrategy initialization failed with the  SimpleSnitch. I have never tested this SimpleSnitch with elassandra, and i can try to fix this in august. Right now, you could use the GossipPropertyFileSnitch even in a single node configuration. Thanks'.
