### ISSUE TITLE
Error Opening zip file or JAR manifest missing jamm-0.3.0.jar

### ISSUE THREAD

**Issue by diegopacheco** [strapdata/elassandra#48]
@vroyer 

When I git clone elasandra and after the build. I tried to run Cassandra I got this error:

Java version: 1.8.0_102-b14

``` bash
[ec2-user@ip-172-28-198-99 bin]$ ./cassandra
[ec2-user@ip-172-28-198-99 bin]$ Error opening zip file or JAR manifest missing : ./../lib/jamm-0.3.0.jar
Error occurred during initialization of VM
agent library failed to init: instrument
```

Cheers,
Diego Pacheco

**Comment by vroyer** [comment]
Hi Diego,

jamm is a cassandra dependency. If you build from source with maven, it is automatically downloaded by maven, but it seems to be corrupted, or unreadable ?

Regards,
Vincent.

**Comment by diegopacheco** [comment]
@vroyer 

should I try rebuild again?

**Comment by vroyer** [comment]
Maybe try mvn dependency:purge-local-repository to re-download jamm.

**Comment by diegopacheco** [comment]
@vroyer 

I runned:

``` bash
mvn dependency:purge-local-repository
mvn clean package -Dmaven.test.skip=true  -Dcassandra.home=/home/ec2-user/cass
andra
```

Build as successful but the issue persist.

**Comment by vroyer** [comment]
Sorry, i can’t reproduce your error (git clone, mvn package, start cassandra is OK). 
You should set your CASSANDRA_HOME=<your elassandra install dir> to get an absolute path to jamm.
Then your JVM should start with  -javaagent:<your elassandra install dir>/lib/jamm-0.3.0.jar

Also check your files and directory rights….
Thanks,
Vincent.

**Comment by diegopacheco** [comment]
@vroyer 

``` bash
[ec2-user@ip-172-28-198-16 bin]$ ./cassandra
[ec2-user@ip-172-28-198-16 bin]$ Error: Could not find or load main class org.apache.cassandra.service.CassandraDaemon

[ec2-user@ip-172-28-198-16 bin]$
[ec2-user@ip-172-28-198-16 bin]$
[ec2-user@ip-172-28-198-16 bin]$ ls /home/ec2-user/cassandra
bin                       CHANGES.txt      debian                       examples   lib          NEWS.txt    README.asc  tools build.properties.default  conf             doc                          ide        LICENSE.txt  NOTICE.txt  src
build.xml                 CONTRIBUTING.md  eclipse_compiler.properties  interface  logs         pylib       test
[ec2-user@ip-172-28-198-16 bin]$ ./cassandra -javaagent:/home/ec2-user/elassandra/lib/jamm-0.3.0.jar
getopt: invalid option -- 'j'
getopt: invalid option -- 'a'
getopt: invalid option -- 'a'
getopt: invalid option -- 'a'
getopt: invalid option -- 'g'
getopt: invalid option -- 'n'
getopt: invalid option -- 't'
getopt: invalid option -- ':'
getopt: invalid option -- '/'
getopt: invalid option -- 'o'
getopt: invalid option -- 'm'
getopt: invalid option -- '/'
getopt: invalid option -- 'c'
getopt: invalid option -- '2'
getopt: invalid option -- '-'
getopt: invalid option -- 'u'
getopt: invalid option -- 's'
getopt: invalid option -- 'r'
getopt: invalid option -- '/'
getopt: invalid option -- 'l'
getopt: invalid option -- 'a'
getopt: invalid option -- 's'
getopt: invalid option -- 's'
getopt: invalid option -- 'a'
getopt: invalid option -- 'n'
getopt: invalid option -- 'r'
getopt: invalid option -- 'a'
getopt: invalid option -- '/'
getopt: invalid option -- 'l'
getopt: invalid option -- 'i'
getopt: invalid option -- '/'
getopt: invalid option -- 'j'
getopt: invalid option -- 'a'
getopt: invalid option -- 'm'
getopt: invalid option -- 'm'
getopt: invalid option -- '-'
getopt: invalid option -- '0'
getopt: invalid option -- '.'
getopt: invalid option -- '3'
getopt: invalid option -- '.'
getopt: invalid option -- '0'
getopt: invalid option -- '.'
getopt: invalid option -- 'j'
getopt: invalid option -- 'a'
getopt: invalid option -- 'r'
Error: Could not find or load main class org.apache.cassandra.tools.GetVersion
[ec2-user@ip-172-28-198-16 bin]$
```

**Comment by vroyer** [comment]
Hi Diego,

You should not run bin/cassandra from your build directory, but, after your build succeed, deploy the target/release/elassandra-x.X.X.zip, and then 
set CASSANDRA_HOME=<your_deploy_dir>
and run <your_deploy_dir>/bin/cassandra -e to run elassandra.

Thanks,
Vincent.

**Comment by diegopacheco** [comment]
@vroyer 

``` bash
[ec2-user@ip-172-28-198-16 elassandra]$ bin/cassandra -e
Starting with Elasticsearch enabled.
[ec2-user@ip-172-28-198-16 elassandra]$ Error: Could not find or load main class org.apache.cassandra.service.ElassandraDaemon

[ec2-user@ip-172-28-198-16 elassandra]$
```

``` bash
CHANGES.txt  dependency-reduced-pom.xml  doc           LICENSE.txt  pom.xml     src        tests
[ec2-user@ip-172-28-198-16 elassandra]$ bin/cassandra -e -javaagent:/home/ec2-user/elassandra/lib/jamm-0.3.0.jar
getopt: invalid option -- 'j'
getopt: invalid option -- 'a'
getopt: invalid option -- 'a'
getopt: invalid option -- 'a'
getopt: invalid option -- 'g'
getopt: invalid option -- 'n'
getopt: invalid option -- 't'
getopt: invalid option -- ':'
getopt: invalid option -- '/'
getopt: invalid option -- 'o'
getopt: invalid option -- 'm'
getopt: invalid option -- '/'
getopt: invalid option -- 'c'
getopt: invalid option -- '2'
getopt: invalid option -- '-'
getopt: invalid option -- 'u'
getopt: invalid option -- 's'
getopt: invalid option -- 'r'
getopt: invalid option -- '/'
getopt: invalid option -- 'l'
getopt: invalid option -- 'a'
getopt: invalid option -- 's'
getopt: invalid option -- 's'
getopt: invalid option -- 'a'
getopt: invalid option -- 'n'
getopt: invalid option -- 'r'
getopt: invalid option -- 'a'
getopt: invalid option -- '/'
getopt: invalid option -- 'l'
getopt: invalid option -- 'i'
getopt: invalid option -- '/'
getopt: invalid option -- 'j'
getopt: invalid option -- 'a'
getopt: invalid option -- 'm'
getopt: invalid option -- 'm'
getopt: invalid option -- '-'
getopt: invalid option -- '0'
getopt: invalid option -- '.'
getopt: invalid option -- '3'
getopt: invalid option -- '.'
getopt: invalid option -- '0'
getopt: invalid option -- '.'
getopt: invalid option -- 'j'
getopt: invalid option -- 'a'
getopt: invalid option -- 'r'
Starting with Elasticsearch enabled.
Error: Could not find or load main class org.apache.cassandra.tools.GetVersion
[ec2-user@ip-172-28-198-16 elassandra]$


```

``` bash
[ec2-user@ip-172-28-198-16 elassandra]$ export CASSANDRA_HOME=/home/ec2-user/elassandra
[ec2-user@ip-172-28-198-16 elassandra]$ ls /home/ec2-user/elassandra
bin          conf                        distribution  images       NOTICE.txt  README.md  target
CHANGES.txt  dependency-reduced-pom.xml  doc           LICENSE.txt  pom.xml     src        tests
[ec2-user@ip-172-28-198-16 elassandra]$ bin/cassandra -e
Starting with Elasticsearch enabled.
[ec2-user@ip-172-28-198-16 elassandra]$ Error opening zip file or JAR manifest missing : /home/ec2-user/elassandra/lib/jamm-0.3.0.jar
Error occurred during initialization of VM
agent library failed to init: instrument

[ec2-user@ip-172-28-198-16 elassandra]$
```

**Comment by vroyer** [comment]
This class should be in <your_install_dir>/lib/elassandra-2.1.1-X.jar.

After unzip elassandra-2.1.1-18.zip, here is what i do in order to start elassandra :

vroyer@MBP-de-Vincent:~/Dev/workspace/elassandra-2.1.1/target/releases/elassandra-2.1.1-18$ ls
CHANGES.txt  LICENSE.txt  NOTICE.txt   README.md    bin/         conf/        data/        etc/         lib/         logs/        plugins/     pylib/       tools/       work/
vroyer@MBP-de-Vincent:~/Dev/workspace/elassandra-2.1.1/target/releases/elassandra-2.1.1-18$ export CASSANDRA_HOME=$PWD
vroyer@MBP-de-Vincent:~/Dev/workspace/elassandra-2.1.1/target/releases/elassandra-2.1.1-18$ bin/cassandra -e
Starting with Elasticsearch enabled.
vroyer@MBP-de-Vincent:~/Dev/workspace/elassandra-2.1.1/target/releases/elassandra-2.1.1-18$ objc[19880]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
CompilerOracle: inline org/apache/cassandra/db/AbstractNativeCell.compareTo (Lorg/apache/cassandra/db/composites/Composite;)I
CompilerOracle: inline org/apache/cassandra/db/composites/AbstractSimpleCellNameType.compareUnsigned (Lorg/apache/cassandra/db/composites/Composite;Lorg/apache/cassandra/db/composites/Composite;)I
CompilerOracle: inline org/apache/cassandra/io/util/Memory.checkBounds (JJ)V
CompilerOracle: inline org/apache/cassandra/io/util/SafeMemory.checkBounds (JJ)V
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compare (Ljava/nio/ByteBuffer;[B)I
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compare ([BLjava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compareUnsigned (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/lang/Object;JILjava/lang/Object;JI)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/lang/Object;JILjava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I

**Comment by diegopacheco** [comment]
@vroyer 

Thanks - now is working :-)

**Comment by vroyer** [comment]
Hi Diego,
You can also load some shell aliases to work quicker with elassandra like this 👍 
$export NODE="<your_elassandra_node_ip_address>"
$. bin/shortcuts-env.sh

Then for exemple:
$ state
{
  "cluster_name" : "Test Cluster",
  "version" : 7,
  "state_uuid" : "7EgGpZVERwWXerKSp4qi-Q",
......

$ indices
green  open   my_index   1   0          2            0      3.3kb          3.3kb 
green  open   my_map     1   0          1            2      3.3kb          3.3kb 
green  open   profiles   1   0          0            0        71b            71b 
green  open   twitter    1   0          4            0     11.1kb         11.1kb 
green  open   vm_index   1   0          0            0        71b            71b
