### ISSUE TITLE
Elassandra on Top of Hadoop

### ISSUE THREAD

**Issue by jed-ob** [strapdata/elassandra#54]
Is there any reference I could go to integrate Elassandra to Hadoop? thanks

**Comment by vroyer** [comment]
I have released a modified version of the Elasticsearch-Hadoop connector for Elassandra, see https://github.com/vroyer/elasticsearch-hadoop . It should also work with hadoop because the  modified code is a common for for spark, hive, pig....but not yet tested. 
Otherwise, you can use any hadoop connector for cassandra 2.2.

**Comment by vroyer** [comment]
Strapdata provides the Elasticsearch-Hadoop connector for Elassandra at [https://github.com/strapdata/elasticsearch-hadoop](https://github.com/strapdata/elasticsearch-hadoop). See its documentation for integration with Hadoop.
