### ISSUE TITLE
What is the correct way to map existing geo_point table? 

### ISSUE THREAD

**Issue by arkataja** [strapdata/elassandra#76]
Not sure whether this is an issue but couldn't find solution from the docs. I have created type and table directly to Cassandra like this:

CREATE TYPE IF NOT EXISTS geo_point (
	lat double,
	lon double
);

CREATE TABLE IF NOT EXISTS points (
	name text,
	location LIST<FROZEN<geo_point>>,
	PRIMARY KEY (name)
);

And then I try to map it with command:

`
curl -XPUT http://localhost:9200/<index_name>/_mapping/points -d '{ 
    "points" : { 
        "properties": { 
            "name" : { "type" : "string" },
            "location": { 
                "type": "geo_point" 
            } 
        } 
    }
}'
`

The result of the call is always *Expected map for property [fields] on field [type] but got a class java.lang.String. Status 400.* What is the correct way to map this? I tried also with plain

`
curl -XPUT http://localhost:9200/<index_name>/_mapping/points -d '
{ 
    "points" : { 
        "discover" : ".*"
    }
}'
`

with the same result. Also second question, when creating type from ES the "_id" column gets created to Cassandra table. But if I create table from Cassandra and then map it from ES there's no "_id" - column visible. How is it so?

**Comment by vroyer** [comment]
You can create your CQL table by creating an ES mapping like this :
$curl -XPUT http://localhost:9200/test/_mapping/points -d '{ "points" : { "properties": { "name" : { "type" : "string" }, "location": { "type": "geo_point" } } } }'

Then you should get the following cassandra schema :

cqlsh> desc KEYSPACE test ;

CREATE KEYSPACE test WITH replication = {'class': 'NetworkTopologyStrategy', 'dc1': '1'}  AND durable_writes = true;

CREATE TYPE test.geo_point (
    lat double,
    lon double
);

CREATE TABLE test.points (
    "_id" text PRIMARY KEY,
    location list<frozen<geo_point>>,
    name list<text>
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = 'Auto-created by Elassandra'
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
CREATE CUSTOM INDEX elastic_points_location_idx ON test.points (values(location)) USING 'org.elassandra.index.ExtendedElasticSecondaryIndex';
CREATE CUSTOM INDEX elastic_points_name_idx ON test.points (values(name)) USING 'org.elassandra.index.ExtendedElasticSecondaryIndex';

Unfortunately, discovering a geo_point mapping from CQL is not currently possible, because geo_point is stored in a User Defined Type as any other nested types (There is no more bijection between ES mapping and CQL schema).
In this case, you can explicitly add the geo_point mapping like this (regex discover all but the location field).

$curl -XPUT http://localhost:9200/test/_mapping/points -d ' { "points" : { "discover" : "^((?!location).*)", "properties": { "location": { "type": "geo_point", "cql_collection":"list" } } } }'

And you get the mapping :
$get "test?pretty"
{
  "test" : {
    "aliases" : { },
    "mappings" : {
      "points" : {
        "properties" : {
          "location" : {
            "type" : "geo_point"
          },
          "name" : {
            "type" : "string",
            "index" : "not_analyzed"
          }
        }
      }
    },
    "settings" : {
      "index" : {
        "creation_date" : "1485211043021",
        "number_of_shards" : "1",
        "number_of_replicas" : "0",
        "uuid" : "Oh6jpfTmRUSkFLl9FqUwLQ",
        "version" : {
          "created" : "2040299"
        }
      }
    },
    "warmers" : { }
  }
}

Finally for your last question, when the underlying cassandra table does not yet exists, ES creates a new table with a text primary key named « _id". 
But if the underlying table already exists, document id is a text representation of its primary key. 
If the primary key is a composite key, _id is a string representation of a JSON array (ex:  [‘a’,1]).


> curl -XPUT http://localhost:9200/test/_mapping/points -d ' { "points" : { "discover" : ".*" } }'
>

**Comment by arkataja** [comment]
Ok, thanks for the info. Continuing evaluation.
